/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Announcement = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'date' : IDL.Text,
  'message' : IDL.Text,
});
export const BracketSlot = IDL.Record({
  'id' : IDL.Nat,
  'team1' : IDL.Text,
  'team2' : IDL.Text,
});
export const Bracket = IDL.Record({
  'qf' : IDL.Vec(BracketSlot),
  'sf' : IDL.Vec(BracketSlot),
  'final' : BracketSlot,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const LeaderboardRow = IDL.Record({
  'd' : IDL.Nat,
  'l' : IDL.Nat,
  'w' : IDL.Nat,
  'ga' : IDL.Nat,
  'gf' : IDL.Nat,
  'id' : IDL.Nat,
  'played' : IDL.Nat,
  'player' : IDL.Text,
  'points' : IDL.Nat,
});
export const MatchResult = IDL.Record({
  'id' : IDL.Nat,
  'team1' : IDL.Text,
  'team2' : IDL.Text,
  'score1' : IDL.Nat,
  'score2' : IDL.Nat,
});
export const Poll = IDL.Record({ 'id' : IDL.Nat, 'matchup' : IDL.Text });
export const TournamentSettings = IDL.Record({
  'status' : IDL.Text,
  'maxSlots' : IDL.Nat,
  'entryFee' : IDL.Text,
  'dateTime' : IDL.Text,
});
export const SlotRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'submittedAt' : IDL.Int,
  'playerName' : IDL.Text,
  'slotNumber' : IDL.Nat,
});
export const Slot = IDL.Record({ 'id' : IDL.Nat, 'player' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveSlotRequest' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getBracket' : IDL.Func([], [Bracket], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardRow)], ['query']),
  'getMatchResults' : IDL.Func([], [IDL.Vec(MatchResult)], ['query']),
  'getPolls' : IDL.Func([], [IDL.Vec(Poll)], ['query']),
  'getRules' : IDL.Func([], [IDL.Text], ['query']),
  'getSettings' : IDL.Func([], [TournamentSettings], ['query']),
  'getSlotRequests' : IDL.Func([], [IDL.Vec(SlotRequest)], ['query']),
  'getSlots' : IDL.Func([], [IDL.Vec(Slot)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rejectSlotRequest' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAnnouncements' : IDL.Func([IDL.Vec(Announcement)], [], []),
  'setBracket' : IDL.Func([Bracket], [], []),
  'setLeaderboard' : IDL.Func([IDL.Vec(LeaderboardRow)], [], []),
  'setMatchResults' : IDL.Func([IDL.Vec(MatchResult)], [], []),
  'setPolls' : IDL.Func([IDL.Vec(Poll)], [], []),
  'setRules' : IDL.Func([IDL.Text], [], []),
  'setSlots' : IDL.Func([IDL.Vec(Slot)], [], []),
  'submitSlotRequest' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
  'updateSettings' : IDL.Func([TournamentSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Announcement = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'date' : IDL.Text,
    'message' : IDL.Text,
  });
  const BracketSlot = IDL.Record({
    'id' : IDL.Nat,
    'team1' : IDL.Text,
    'team2' : IDL.Text,
  });
  const Bracket = IDL.Record({
    'qf' : IDL.Vec(BracketSlot),
    'sf' : IDL.Vec(BracketSlot),
    'final' : BracketSlot,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const LeaderboardRow = IDL.Record({
    'd' : IDL.Nat,
    'l' : IDL.Nat,
    'w' : IDL.Nat,
    'ga' : IDL.Nat,
    'gf' : IDL.Nat,
    'id' : IDL.Nat,
    'played' : IDL.Nat,
    'player' : IDL.Text,
    'points' : IDL.Nat,
  });
  const MatchResult = IDL.Record({
    'id' : IDL.Nat,
    'team1' : IDL.Text,
    'team2' : IDL.Text,
    'score1' : IDL.Nat,
    'score2' : IDL.Nat,
  });
  const Poll = IDL.Record({ 'id' : IDL.Nat, 'matchup' : IDL.Text });
  const TournamentSettings = IDL.Record({
    'status' : IDL.Text,
    'maxSlots' : IDL.Nat,
    'entryFee' : IDL.Text,
    'dateTime' : IDL.Text,
  });
  const SlotRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'submittedAt' : IDL.Int,
    'playerName' : IDL.Text,
    'slotNumber' : IDL.Nat,
  });
  const Slot = IDL.Record({ 'id' : IDL.Nat, 'player' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveSlotRequest' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getBracket' : IDL.Func([], [Bracket], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardRow)], ['query']),
    'getMatchResults' : IDL.Func([], [IDL.Vec(MatchResult)], ['query']),
    'getPolls' : IDL.Func([], [IDL.Vec(Poll)], ['query']),
    'getRules' : IDL.Func([], [IDL.Text], ['query']),
    'getSettings' : IDL.Func([], [TournamentSettings], ['query']),
    'getSlotRequests' : IDL.Func([], [IDL.Vec(SlotRequest)], ['query']),
    'getSlots' : IDL.Func([], [IDL.Vec(Slot)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rejectSlotRequest' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAnnouncements' : IDL.Func([IDL.Vec(Announcement)], [], []),
    'setBracket' : IDL.Func([Bracket], [], []),
    'setLeaderboard' : IDL.Func([IDL.Vec(LeaderboardRow)], [], []),
    'setMatchResults' : IDL.Func([IDL.Vec(MatchResult)], [], []),
    'setPolls' : IDL.Func([IDL.Vec(Poll)], [], []),
    'setRules' : IDL.Func([IDL.Text], [], []),
    'setSlots' : IDL.Func([IDL.Vec(Slot)], [], []),
    'submitSlotRequest' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
    'updateSettings' : IDL.Func([TournamentSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };