/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Poll {
  'question' : string,
  'votes' : Array<bigint>,
  'options' : Array<string>,
}
export type Time = bigint;
export interface Tournament {
  'maxSlots' : bigint,
  'name' : string,
  'slots' : Array<string>,
  'entryFee' : bigint,
  'dateTime' : Time,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Winner { 'playerName' : string, 'position' : bigint }
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addWinner' : ActorMethod<[string, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrUpdatePoll' : ActorMethod<[string, Array<string>], undefined>,
  'createOrUpdateTournament' : ActorMethod<
    [string, bigint, Time, bigint],
    undefined
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPoll' : ActorMethod<[], [] | [Poll]>,
  'getTournament' : ActorMethod<[], [] | [Tournament]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWinners' : ActorMethod<[], Array<Winner>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateSlots' : ActorMethod<[Array<string>], undefined>,
  'voteInPoll' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];