/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Poll = IDL.Record({
  'question' : IDL.Text,
  'votes' : IDL.Vec(IDL.Nat),
  'options' : IDL.Vec(IDL.Text),
});
export const Tournament = IDL.Record({
  'maxSlots' : IDL.Nat,
  'name' : IDL.Text,
  'slots' : IDL.Vec(IDL.Text),
  'entryFee' : IDL.Nat,
  'dateTime' : Time,
});
export const Winner = IDL.Record({
  'playerName' : IDL.Text,
  'position' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addWinner' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdatePoll' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'createOrUpdateTournament' : IDL.Func(
      [IDL.Text, IDL.Nat, Time, IDL.Nat],
      [],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPoll' : IDL.Func([], [IDL.Opt(Poll)], ['query']),
  'getTournament' : IDL.Func([], [IDL.Opt(Tournament)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWinners' : IDL.Func([], [IDL.Vec(Winner)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateSlots' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'voteInPoll' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Poll = IDL.Record({
    'question' : IDL.Text,
    'votes' : IDL.Vec(IDL.Nat),
    'options' : IDL.Vec(IDL.Text),
  });
  const Tournament = IDL.Record({
    'maxSlots' : IDL.Nat,
    'name' : IDL.Text,
    'slots' : IDL.Vec(IDL.Text),
    'entryFee' : IDL.Nat,
    'dateTime' : Time,
  });
  const Winner = IDL.Record({ 'playerName' : IDL.Text, 'position' : IDL.Nat });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addWinner' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdatePoll' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'createOrUpdateTournament' : IDL.Func(
        [IDL.Text, IDL.Nat, Time, IDL.Nat],
        [],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPoll' : IDL.Func([], [IDL.Opt(Poll)], ['query']),
    'getTournament' : IDL.Func([], [IDL.Opt(Tournament)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWinners' : IDL.Func([], [IDL.Vec(Winner)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateSlots' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'voteInPoll' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };